-- Create seeds inventory table
begin;

    create table
    if not exists public.seeds
    (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now
    (),
  updated_at timestamptz not null default now
    (),
  crop_variety_id bigint not null references public.crop_varieties
    (id),
  crop_name text not null,
  variety_name text not null,
  vendor text,
  lot_number text,
  date_received date,
  quantity integer,
  quantity_units text,
  notes text
);

    create index
    if not exists seeds_crop_variety_id_idx on public.seeds
    (crop_variety_id);

    -- RLS
    alter table public.seeds enable row level security;
create policy "seeds: authenticated all" on public.seeds for all to authenticated using
(true) with check
(true);

-- Trigger to auto-update updated_at
create or replace function public.set_updated_at
() returns trigger language plpgsql as $$
begin
  new.updated_at = now
();
return new;
end;
$$;

drop trigger if exists set_seeds_updated_at
on public.seeds;
create trigger set_seeds_updated_at before
update on public.seeds for each row
execute
function public.set_updated_at
();

commit;


